<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.js"></script>

    <style>
        body {
            /* text-align: center; */
            font-family: 'Times New Roman', Times, serif;
            margin-top: 20px;
        }

        input {
            width: 100%;
            padding: 5px;
        }

        h2 {
            margin-left: 33%;
        }

        /* .login:hover{
            background-color: transparent;
        } */
    </style>
</head>
<script>

</script>

<body>
    <?php echo $this->tag->form("/index/addProduct"); ?>
    <div class="row">
        <div class="col">
            <h2 class="text-primary" id="heading"></h2>
            <div id="newRow" class="container"></div>
        </div>
        <div class="col md-4 border border-info bg-dark text-light main">
            <h2>Add Product</h2>


            <p>
                <label for="name">Product Name</label>
                <?php echo $this->tag->textField("product_name"); ?>
            </p>
            <p>
                <label for="email">Category</label>
                <?php echo $this->tag->textField("product_category"); ?>
            </p>
            <p>
                <label for="email">Price</label>
                <?php echo $this->tag->textField("price"); ?>
            </p>
            <p>
                <label for="email">Stock</label>
                <?php echo $this->tag->textField("stock"); ?>
            </p>
            <p>
                <?php echo $msg; ?>
            </p>

            <p>
                <?php echo $this->tag->submitButton(["name" => "addproduct", "value" => "Add Product", "class" => "btn btn-success", "style" => "width:100%; margin-bottom:10px;"]); ?>
                <br><button class="btn btn-primary" id="addRow" type="button">Add More Fields</button>
                <a class="btn btn-outline-danger search" href="/index/productsList" style="margin-left: 35px;">List Product</a>
                <button class="btn btn-info" id="addVariation" type="button" style="float:right;">Add Variations</button>
                <a class="btn btn-light search" href="/order/index" style="margin-left: 100px;">Add Order</a>
                <a class="btn btn-light search" href="/order/list" style="margin-left: 50px; margin-top:5px;">List Order</a>

            </p>

        </div>
        <div class="col">
            <h2 class="text-info" id="heading2"></h2>
            <div id="newVariation" class="container" style="width:100%;"></div>
        </div>
    </div>
    </form>
    <?php
    if ($this->session->get('msg')) {
        echo $this->session->get('msg');
    }
    ?>
    </div>
    <script type="text/javascript">
        // add row 
        $("#addRow").click(function() {
            document.getElementById("heading").innerHTML = "Add More Fields";
            var html = '';
            html += '<div id="inputFormRow">';
            html += '<div class="input-group mb-3">';
            html += '<input type="text" name="field_name[]" class="form-control m-input" placeholder="Field Name" autocomplete="off">';
            html += '<input type="text" name="field_value[]" class="form-control m-input" placeholder="Field Value" autocomplete="off">';

            html += '<div class="input-group-append">';
            html += '<button id="removeRow" type="button" class="btn btn-danger">Remove</button>';
            html += '</div>';
            html += '</div>';

            $('#newRow').append(html);
        });

        // remove row
        $(document).on('click', '#removeRow', function() {
            $(this).closest('#inputFormRow').remove();
        });

        //add variation
        $("#addVariation").click(function() {
            document.getElementById("heading2").innerHTML = "Add Variations";
            var html1 = '';
            html1 += '<div id="inputFormRow">';
            html1 += '<div class="input-group mb-3">';
            html1 += '<input type="number" name="size[]" class="form-control m-input" placeholder="Size" autocomplete="off">';
            html1 += '<input type="text" name="color[]" class="form-control m-input" placeholder="Color" autocomplete="off">';
            html1 += '<input type="number" name="variation_price[]" class="form-control m-input" placeholder="Price" autocomplete="off">';

            html1 += '<div class="input-group-append">';
            html1 += '<button id="removeRow" type="button" class="btn btn-danger">Remove</button>';
            html1 += '</div>';
            html1 += '</div>';

            $('#newVariation').append(html1);
        });
    </script>
</body>

</html>