<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: 'Times New Roman', Times, serif;

        }

        input {
            padding: 10px;
            display: block;
        }

        select {
            padding: 10px;
        }

        label {
            display: block;
        }
    </style>
</head>

<body>
    <div class='container-fluid'>
    <form action="/order/index" method="POST">
        <label for="">Choose Product</label>
        <select name="product" id="product">
            <option value="0" selected disabled hidden>--Select--</option>
            <?php
            foreach ($products as $k => $v) {
            ?>
                <option value=<?php echo $v->_id ?>><?php echo $v->product_name; ?></option>
                
            <?php }

            ?>
        </select>
        <label for="Customer_name">Customer Name</label>
        <input type="text" name="customer_name" placeholder="Customer Name">
        <label for="Customer_name">Quantity</label>
        <input type="number" name="quantity" placeholder="Quantity">
        <input type="submit" value="Place Order" name="add_order" class="btn btn-success">
    </form>
    </div>
    <?php if($msg){
        echo $msg;
    } ?>
</body>

</html>